services:
  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"

  rabbitmq:
    image: rabbitmq:3-management
    ports:
      - "5672:5672"
      - "15672:15672"

  backend:
    build:
      context: ./backend
    ports:
      - "3000:3000/tcp"
    environment:
      PORT: "3000"
      HOST: "0.0.0.0"
      REDIS_HOST: "redis"
      REDIS_PORT: "6379"
      RABBITMQ_URL: "amqp://guest:guest@rabbitmq:5672"
    depends_on:
      - redis
      - rabbitmq

  web-frontend:
    build:
      context: ./fitstack-frontend
      args:
        REACT_APP_API_URL: http://localhost:3000
    ports:
      - "3001:80/tcp"
    depends_on:
      - backend
